# Generated by Django 4.2.29 on 2026-07-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisonnier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cellule', models.CharField(max_length=20)),
                ('motif', models.TextField()),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField()),
                ('statut', models.CharField(choices=[('encours', 'En cours'), ('liberable', 'Libérable'), ('libere', 'Libéré')], max_length=20)),
            ],
        ),
    ]
