# Generated by Django 4.2.29 on 2026-07-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisonniers', '0002_prisonnier_age_prisonnier_document_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisonnier',
            name='etat_civil',
            field=models.CharField(blank=True, choices=[('Celibataire', 'Celibataire'), ('Marie', 'Marie'), ('Divorce', 'Divorce'), ('Veuf', 'Veuf')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prisonnier',
            name='numero_prisonnier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prisonnier',
            name='postnom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
