# Generated by Django 4.2.29 on 2026-07-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisonniers', '0003_prisonnier_etat_civil_prisonnier_numero_prisonnier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisonnier',
            name='alarme_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prisonnier',
            name='plaignant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prisonnier',
            name='temoin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
